### ISSUE TITLE
feature request:  submit / get on the list of  official asdf plugins

### ISSUE THREAD

**Issue by bitfrost** [phrase/asdf-phrase#1]
https://github.com/asdf-vm/asdf-plugins

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20) and we can take more direct action toward finding a solution.
